sudo: required
language: generic
dist: focal

matrix:
  include:
    - addons:
        apt:
          packages:
            - clang-10
      env: CC=clang-10 CXX=clang++-10
    - addons:
        apt:
          packages:
            - clang-9
      env: CC=clang-9 CXX=clang++-9
    - addons:
        apt:
          packages:
            - clang-8
      env: CC=clang-8 CXX=clang++-8
    - addons:
        apt:
          packages:
            - clang-7
      env: CC=clang-7 CXX=clang++-7
    - addons:
        apt:
          packages:
            - clang-6.0
      env: CC=clang-6.0 CXX=clang++-6.0
    - addons:
        apt:
          packages:
            - gcc-10
            - g++-10
      env: CC=gcc-10 CXX=g++-10
    - addons:
        apt:
          packages:
            - gcc-9
            - g++-10
      env: CC=gcc-9 CXX=g++-9
    - addons:
        apt:
          packages:
            - gcc-8
            - g++-8
      env: CC=gcc-8 CXX=g++-8
    - addons:
        apt:
          packages:
            - gcc-7
            - g++-7
      env: CC=gcc-7 CXX=g++-7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libev-dev qtbase5-dev libdrm-dev

script:
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_FLAGS="-std=c++14" -DCMAKE_INSTALL_PREFIX=$HOME ..
  - make install
